# Isanai paths
ISANAI_HOME=~/.zsh/isanai
ISANAI_CONF=~/.zsh/.conf

ISANAI_PLUGIN_LIST_FILE=$ISANAI_HOME/plugin_list.zsh
ISANAI_SETTINGS_FILE=$ISANAI_HOME/settings.zsh
ISANAI_ZPLUG_FILE=$ISANAI_HOME/zplug.zsh
ISANAI_ALIAS_FILE=$ISANAI_HOME/aliases.zsh
ISANAI_TASK_FILE=$ISANAI_HOME/task.zsh
ISANAI_KEY_FILE=$ISANAI_HOME/key.zsh

ISANAI_PLUGIN_CONFIG_DIR=$ISANAI_HOME/plugin
